In [3]:
import cv2 
import numpy as np

In [10]:
img = cv2.imread('smarties.png')
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(imgray, 127,255,1)
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
print("Number of contours = " + str(len(contours)))
print(contours[0])

Number of contours = 31
[[[ 72 337]]

 [[ 71 338]]

 [[ 70 338]]

 [[ 69 338]]

 [[ 68 339]]

 [[ 67 339]]

 [[ 66 340]]

 [[ 65 340]]

 [[ 64 341]]

 [[ 63 342]]

 [[ 62 343]]

 [[ 61 344]]

 [[ 60 345]]

 [[ 59 346]]

 [[ 58 347]]

 [[ 57 348]]

 [[ 57 349]]

 [[ 56 350]]

 [[ 56 351]]

 [[ 55 352]]

 [[ 55 353]]

 [[ 54 354]]

 [[ 54 355]]

 [[ 55 355]]

 [[ 56 355]]

 [[ 57 355]]

 [[ 58 355]]

 [[ 59 355]]

 [[ 60 355]]

 [[ 61 355]]

 [[ 62 355]]

 [[ 63 354]]

 [[ 64 354]]

 [[ 65 355]]

 [[ 66 355]]

 [[ 67 355]]

 [[ 68 355]]

 [[ 69 355]]

 [[ 70 355]]

 [[ 71 355]]

 [[ 72 355]]

 [[ 73 355]]

 [[ 74 355]]

 [[ 75 355]]

 [[ 76 355]]

 [[ 77 355]]

 [[ 78 355]]

 [[ 79 355]]

 [[ 80 355]]

 [[ 81 355]]

 [[ 82 355]]

 [[ 83 355]]

 [[ 84 355]]

 [[ 85 355]]

 [[ 86 355]]

 [[ 87 355]]

 [[ 88 355]]

 [[ 88 354]]

 [[ 89 353]]

 [[ 90 353]]

 [[ 91 353]]

 [[ 92 353]]

 [[ 93 354]]

 [[ 94 354]]

 [[ 95 355]]

 [[ 96 355]]

 [[ 97 355]]

 [[ 98 355]]

 [[ 99 355]]

 [[100 355

In [7]:
cv2.drawContours(img, contours, -1, (0,255,255), 3)
cv2.drawContours(imgray, contours, -1, (0,255,255),3)
cv2.drawContours(thresh, contours, -1, (0,255,255),3)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [8]:
cv2.imshow('Image', img)
cv2.imshow('image GRAY', imgray)
cv2.imshow('Image Binary', thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()