In [1]:
import numpy as np
import cv2 as cv

In [2]:
cap = cv.VideoCapture('slow_traffic_small.mp4')
ret, frame = cap.read()

x, y, width, height = 300, 200, 100, 50
track_window = (x, y, width, height)

roi = frame[y:y+height, x:x+width]
hsv_roi = cv.cvtColor(roi, cv.COLOR_BGR2HSV)

mask = cv.inRange(hsv_roi, np.array((0., 60., 32.)), np.array((180., 255., 255)))
#mask.shape = (50, 100)

roi_hist = cv.calcHist([hsv_roi], [0], mask, [180], [0,180])

cv.normalize(roi_hist, roi_hist, 0, 255, cv.NORM_MINMAX)

term_crit = (cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1)
cv.imshow('roi', roi)

In [3]:
while(1):
    ret, frame = cap.read()
    if ret == True:
        
        hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
        dst = cv.calcBackProject([hsv], [0], roi_hist, [0,180], 1)
        
        ret, track_window = cv.CamShift(dst, track_window, term_crit)
        
        pts = cv.boxPoints(ret) #找出矩形4個頂點
        print(pts)
        pts = np.int0(pts)

        final_image = cv.polylines(frame, [pts], True, (0,255,255), 2) #非填充多邊形
        
        cv.imshow('dst', dst)
        cv.imshow('final_image', final_image)
        k = cv.waitKey(30) & 0xFF
        if k == 27:
            break
    
    else:
        break
cap.release()
cv.destroyAllWindows()

[[315.2072  187.89851]
 [398.84894 194.02357]
 [396.7928  222.10149]
 [313.15106 215.97643]]
[[319.61652 191.50002]
 [394.9226  196.85487]
 [393.38348 218.49998]
 [318.0774  213.14513]]
[[321.63092 192.25986]
 [394.95935 198.23984]
 [393.36908 217.74014]
 [320.04065 211.76016]]
[[320.7584  193.52069]
 [393.6008  198.82953]
 [392.2416  217.47931]
 [319.3992  212.17047]]
[[321.82224 194.5947 ]
 [393.54575 199.8956 ]
 [392.17776 218.4053 ]
 [320.45425 213.1044 ]]
[[320.9231  193.14307]
 [399.94702 200.96628]
 [398.0769  219.85693]
 [319.05298 212.03372]]
[[321.89383 193.63565]
 [400.0682  200.7232 ]
 [398.10617 222.36435]
 [319.9318  215.2768 ]]
[[321.41946 192.9755 ]
 [401.00034 200.98657]
 [398.58054 225.0245 ]
 [318.99966 217.01343]]
[[323.20358 194.14804]
 [403.91214 201.94138]
 [401.79642 223.85196]
 [321.08786 216.05862]]
[[321.38187 193.90353]
 [404.7753  197.7038 ]
 [403.61813 223.09647]
 [320.2247  219.2962 ]]
[[317.10464 194.3696 ]
 [406.2131  195.4097 ]
 [405.89536 222.6304 ]
 