In [1]:
import numpy as np
import cv2 as cv

In [2]:
cap = cv.VideoCapture('slow_traffic_small.mp4')
ret, frame = cap.read()

x, y, width, height = 300, 200, 100, 50
track_window = (x, y, width, height)

roi = frame[y:y+height, x:x+width]
hsv_roi = cv.cvtColor(roi, cv.COLOR_BGR2HSV)

mask = cv.inRange(hsv_roi, np.array((0., 60., 32.)), np.array((180., 255., 255)))
#mask.shape = (50, 100)

roi_hist = cv.calcHist([hsv_roi], [0], mask, [180], [0,180])

cv.normalize(roi_hist, roi_hist, 0, 255, cv.NORM_MINMAX)

term_crit = (cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1)
cv.imshow('roi', roi)
#cv.imwrite('template2.jpg',roi)

In [3]:
#roi2 = cv.imread('green.jpg')
#print(roi2.shape)


#x2, y2, width2, height2 = 50, 70, 30, 50
x2, y2, width2, height2 = 165, 130, 15, 30
track_window2 = (x2, y2, width2, height2)

roi2 = frame[y2:y2+height2, x2:x2+width2]
hsv_roi2 = cv.cvtColor(roi2, cv.COLOR_BGR2HSV)

#mask2 = cv.inRange(hsv_roi2, np.array((15., 30., 15.)), np.array((90., 200., 90.)))
mask2 = cv.inRange(hsv_roi2, np.array((20., 30., 20.)), np.array((90., 255., 90.)))
roi_hist2 = cv.calcHist([hsv_roi2], [0], mask2, [180], [0,180])

cv.normalize(roi_hist2, roi_hist2, 0, 255, cv.NORM_MINMAX)

term_crit2 = (cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1)
cv.imshow('roi2', roi2)

In [4]:
while(1):
    ret, frame = cap.read()
    if ret == True:
        
        hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
        dst = cv.calcBackProject([hsv], [0], roi_hist, [0,180], 1)
        
        dst2 = cv.calcBackProject([hsv], [0], roi_hist2, [0,180], 1)
        
        ret, track_window = cv.CamShift(dst, track_window, term_crit)
        
        ret2, track_window2 = cv.CamShift(dst2, track_window2, term_crit2)
        
        pts = cv.boxPoints(ret) #找出矩形4個頂點
        print(pts)
        pts = np.int0(pts)
        
        pts2 = cv.boxPoints(ret2) #找出矩形4個頂點
        print(pts2)
        pts2 = np.int0(pts2)

        final_image = cv.polylines(frame, [pts], True, (0,255,255), 2) #非填充多邊形
        final_image2 = cv.polylines(final_image, [pts2], True, (0,255,255), 2) #非填充多邊形
        
        cv.imshow('dst', dst)
        cv.imshow('final_image', final_image2)
        k = cv.waitKey(30) & 0xFF
        if k == 27:
            break
    
    else:
        break
cap.release()
cv.destroyAllWindows()

[[315.2072  187.89851]
 [398.84894 194.02357]
 [396.7928  222.10149]
 [313.15106 215.97643]]
[[169. 131.]
 [171. 131.]
 [171. 133.]
 [169. 133.]]
[[319.61652 191.50002]
 [394.9226  196.85487]
 [393.38348 218.49998]
 [318.0774  213.14513]]
[[169. 131.]
 [171. 131.]
 [171. 133.]
 [169. 133.]]
[[321.63092 192.25986]
 [394.95935 198.23984]
 [393.36908 217.74014]
 [320.04065 211.76016]]
[[175.      144.23607]
 [175.      139.76393]
 [177.      139.76393]
 [177.      144.23607]]
[[320.7584  193.52069]
 [393.6008  198.82953]
 [392.2416  217.47931]
 [319.3992  212.17047]]
[[170.39737 129.08066]
 [186.49707 137.1305 ]
 [185.60263 138.91934]
 [169.50293 130.8695 ]]
[[321.82224 194.5947 ]
 [393.54575 199.8956 ]
 [392.17776 218.4053 ]
 [320.45425 213.1044 ]]
[[162.4778  135.12048]
 [182.5512  147.16452]
 [181.5222  148.87952]
 [161.4488  136.83548]]
[[320.9231  193.14307]
 [399.94702 200.96628]
 [398.0769  219.85693]
 [319.05298 212.03372]]
[[167.6725  154.04431]
 [168.37312 129.58463]
 [181.3275 